name: rmgpgab-consent-management-api-us-central1-varnarc25-spec-cosdu
description: Build and deploy consent-management-api with secrets
github:
  owner: varnarc25-spec
  name: consent_management
  push:
    branch: ^main$
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
serviceAccount: projects/myweb-503314/serviceAccounts/414895350436-compute@developer.gserviceaccount.com
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_PROJECT_ID: myweb-503314
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: us-central1
  _PLATFORM: managed
  _SERVICE_NAME: consent-management-api
  _TRIGGER_ID: eec2b72c-9c0e-4644-a710-b9605556dfa5
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - consent-management-api
build:
  images:
    - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  options:
    logging: CLOUD_LOGGING_ONLY
    substitutionOption: ALLOW_LOOSE
  steps:
    - name: gcr.io/cloud-builders/docker
      id: Build
      args:
        - build
        - --no-cache
        - -t
        - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
        - -f
        - docker/Dockerfile.api
        - .
    - name: gcr.io/cloud-builders/docker
      id: Push
      args:
        - push
        - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
      id: Deploy
      entrypoint: gcloud
      args:
        - run
        - services
        - update
        - $_SERVICE_NAME
        - --platform=managed
        - --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
        - --region=$_DEPLOY_REGION
        - --port=8080
        - --memory=2Gi
        - --cpu=2
        - --no-cpu-throttling
        - --startup-probe=initialDelaySeconds=30,timeoutSeconds=5,periodSeconds=10,failureThreshold=18,httpGet.path=/api/v1/health,httpGet.port=8080
        - --set-env-vars=NODE_ENV=production,API_PREFIX=api/v1,API_URL=https://consent-management-api-414895350436.us-central1.run.app,ADMIN_URL=https://consent-management-admin-414895350436.us-central1.run.app,WEB_URL=https://consent-management-web-414895350436.us-central1.run.app,EMAIL_VERIFICATION_ENABLED=false,DOMAIN_AUTO_VERIFY=false,AUTH0_DOMAIN=dev-varnarc.us.auth0.com,AUTH0_AUDIENCE=https://api.consent-management.varnarc.com,AUTH0_ISSUER_URL=https://dev-varnarc.us.auth0.com/
        - --set-secrets=CM_DATABASE_URL=CM_DATABASE_URL:latest,JWT_ACCESS_SECRET=JWT_ACCESS_SECRET:latest,JWT_REFRESH_SECRET=JWT_REFRESH_SECRET:latest
        - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
        - --quiet
