# Inline Cloud Build — consent-management-web
# Paste into: Cloud Build → Triggers → Web trigger → Open editor

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '-f'
      - docker/Dockerfile.web
      - '--build-arg'
      - >-
        NEXT_PUBLIC_ADMIN_URL=https://consent-management-admin-414895350436.us-central1.run.app
      - '--build-arg'
      - NEXT_PUBLIC_AUTH0_CONFIGURED=true
      - '--build-arg'
      - NEXT_PUBLIC_AUTH0_CLIENT_ID=9brZ3YvbmdNy4jzCM8g1D0M7ynGuxp8W
      - '--build-arg'
      - AUTH0_DOMAIN=dev-varnarc.us.auth0.com
      - '--build-arg'
      - AUTH0_AUDIENCE=https://api.consent-management.varnarc.com
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--region=$_DEPLOY_REGION'
      - '--port=8080'
      - >-
        --set-env-vars=NODE_ENV=production,APP_BASE_URL=https://consent-management-web-414895350436.us-central1.run.app,AUTH0_DOMAIN=dev-varnarc.us.auth0.com,AUTH0_CLIENT_ID=9brZ3YvbmdNy4jzCM8g1D0M7ynGuxp8W,NEXT_PUBLIC_AUTH0_DOMAIN=dev-varnarc.us.auth0.com,AUTH0_AUDIENCE=https://api.consent-management.varnarc.com,API_URL=https://consent-management-api-414895350436.us-central1.run.app/api/v1,NEXT_PUBLIC_API_URL=https://consent-management-api-414895350436.us-central1.run.app/api/v1,NEXT_PUBLIC_ADMIN_URL=https://consent-management-admin-414895350436.us-central1.run.app,NEXT_PUBLIC_AUTH0_CONFIGURED=true,NEXT_PUBLIC_AUTH0_CLIENT_ID=9brZ3YvbmdNy4jzCM8g1D0M7ynGuxp8W
      - >-
        --set-secrets=cm_auth0_client_secret=cm_auth0_client_secret:latest,AUTH0_SECRET=AUTH0_SECRET:latest
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_PROJECT_ID: myweb-503314
  _PLATFORM: managed
  _SERVICE_NAME: consent-management-web
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _TRIGGER_ID: a8117ed3-cf3e-4e44-884e-8a9f46a2500c
  _AR_REPOSITORY: cloud-run-source-deploy
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - consent-management-web
