export const DEFAULT_CONSENT_CATEGORIES = [
  {
    slug: 'strictly_necessary',
    name: 'Strictly Necessary',
    description: 'Required for the website to function and cannot be switched off.',
    required: true,
    defaultState: 'ENABLED' as const,
    sortOrder: 0,
    isSystem: true,
  },
  {
    slug: 'preferences',
    name: 'Preferences',
    description: 'Remember settings and choices to personalize your experience.',
    required: false,
    defaultState: 'DISABLED' as const,
    sortOrder: 1,
    isSystem: true,
  },
  {
    slug: 'functional',
    name: 'Functional',
    description: 'Enable enhanced functionality such as videos and live chat.',
    required: false,
    defaultState: 'DISABLED' as const,
    sortOrder: 2,
    isSystem: true,
  },
  {
    slug: 'analytics',
    name: 'Analytics',
    description: 'Help us understand how visitors use the website.',
    required: false,
    defaultState: 'DISABLED' as const,
    sortOrder: 3,
    isSystem: true,
  },
  {
    slug: 'performance',
    name: 'Performance',
    description: 'Measure and improve website performance.',
    required: false,
    defaultState: 'DISABLED' as const,
    sortOrder: 4,
    isSystem: true,
  },
  {
    slug: 'marketing',
    name: 'Marketing',
    description: 'Used to deliver relevant ads and marketing campaigns.',
    required: false,
    defaultState: 'DISABLED' as const,
    sortOrder: 5,
    isSystem: true,
  },
  {
    slug: 'social_media',
    name: 'Social Media',
    description: 'Enable social sharing and embedded social content.',
    required: false,
    defaultState: 'DISABLED' as const,
    sortOrder: 6,
    isSystem: true,
  },
  {
    slug: 'unclassified',
    name: 'Unclassified',
    description: 'Cookies that have not yet been categorized.',
    required: false,
    defaultState: 'DISABLED' as const,
    sortOrder: 7,
    isSystem: true,
  },
] as const;

export const DEFAULT_BANNER_CONTENT = {
  title: 'We value your privacy',
  description:
    'We use cookies to improve your experience, analyze site traffic, and personalize content. You can manage your preferences at any time.',
  acceptButton: 'Accept all',
  rejectButton: 'Reject all',
  preferencesButton: 'Manage preferences',
  saveButton: 'Save preferences',
  closeButton: 'Close',
  legalNotice: '',
  footerContent: '',
  privacyPolicyUrl: '',
  cookiePolicyUrl: '',
  layout: 'bottom_bar' as const,
  contentFormat: 'plain' as const,
  behavior: {
    displayOnFirstVisit: true,
    displayAfterConsentExpires: true,
    displayWhenPolicyChanges: true,
    showOnPages: [] as string[],
    excludePages: [] as string[],
    displayDelayMs: 0,
    displayAfterScrollPercent: 0,
    displayAfterInteraction: false,
    blockInteractionUntilChoice: false,
    respectGlobalPrivacyControl: false,
    rememberChoice: true,
    consentExpirationDays: 365,
    allowClose: false,
  },
  theme: {
    primaryColor: '#2563eb',
    backgroundColor: '#ffffff',
    textColor: '#111827',
    buttonTextColor: '#ffffff',
    buttonStyle: 'filled' as const,
    borderRadius: '8px',
    fontFamily: 'system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
    fontSize: '16px',
    spacing: '1rem',
    shadow: '0 10px 30px rgba(0,0,0,.15)',
    overlayOpacity: 0.45,
    logoUrl: '',
    iconUrl: '',
    customCss: '',
  },
  privacyTrigger: {
    enabled: true,
    mode: 'floating_icon' as const,
    label: 'Privacy settings',
    position: 'bottom-right' as const,
    footerSelector: '',
  },
};
